/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        demoBycycle();
        demoMountainBike();
        demoAcmeBycycle();

        demoWildcard();
    }

    public static void demoBycycle() {
        System.out.println("Bicycle Demo");

        SimpleBicycle myBycycle = new SimpleBicycle();
        myBycycle.changeCadence(50);
        myBycycle.speedUp(10);
        myBycycle.changeGear(2);
        myBycycle.printStates();
        myBycycle.speedUp(10);
        myBycycle.changeGear(3);
        myBycycle.printStates();
        myBycycle.applyBrakes(5);
        myBycycle.printStates();
    }

    public static void demoMountainBike() {
        System.out.println("Mountain Bike Demo");

        MountainBike myBycycle = new MountainBike(3, 0, 0, 1);
        myBycycle.changeCadence(50);
        myBycycle.speedUp(10);
        myBycycle.changeGear(2);
        myBycycle.printStates();
        myBycycle.speedUp(10);
        myBycycle.changeGear(3);
        myBycycle.printStates();
        myBycycle.applyBrakes(5);
        myBycycle.printStates();
    }

    public static void demoAcmeBycycle() {
        System.out.println("Acme Bicycle Demo");

        AcmeBicycle myBycycle = new AcmeBicycle();
        myBycycle.changeCadence(50);
        myBycycle.speedUp(10);
        myBycycle.changeGear(2);
        myBycycle.printStates();
        myBycycle.speedUp(10);
        myBycycle.changeGear(3);
        myBycycle.printStates();
        myBycycle.applyBrakes(5);
        myBycycle.printStates();
    }

    public static void demoWildcard() {
        System.out.println("Wildcard Demo");

        Wildcard wildcardDemo = new Wildcard();
        wildcardDemo.demo();
    }
}
