/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "KataJpg";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        if (args.length == 0) {
            System.out.println("Please provide a JPEG file path as an argument.");
            return;
        }

        var reader = new JpgFileReader();
        reader.read(args[0]);
    }
}
